<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="sandeep406701" ignored="4" name="Regression-Suite" tests="87" failures="27" timestamp="09 Jan 2019 10:26:52 GMT" time="9.421" errors="0">
  <testcase name="test_01_verify_placing_an_order" time="2.579" classname="com.rest.api.PlaceOrderApi"/>
  <testcase name="test_02_verify_placing_an_order_at_specific_time" time="0.575" classname="com.rest.api.PlaceOrderApi"/>
  <testcase name="test_03_verify_order_not_placed_with_invalid_time_format" time="0.027" classname="com.rest.api.PlaceOrderApi"/>
  <testcase name="test_03_verify_order_not_placed_with_invalid_time_format" time="0.043" classname="com.rest.api.PlaceOrderApi"/>
  <testcase name="test_03_verify_order_not_placed_with_invalid_time_format" time="0.03" classname="com.rest.api.PlaceOrderApi"/>
  <testcase name="test_03_verify_order_not_placed_with_invalid_time_format" time="0.037" classname="com.rest.api.PlaceOrderApi"/>
  <testcase name="test_03_verify_order_not_placed_with_invalid_time_format" time="0.033" classname="com.rest.api.PlaceOrderApi"/>
  <testcase name="test_03_verify_order_not_placed_with_invalid_time_format" time="0.025" classname="com.rest.api.PlaceOrderApi"/>
  <testcase name="test_04_verify_order_not_placed_with_incorrect_location_of_one_stop" time="0.885" classname="com.rest.api.PlaceOrderApi">
    <failure type="java.lang.AssertionError" message="
Expected: is &amp;lt;400&amp;gt;
     but: was &amp;lt;201&amp;gt;">
      <![CDATA[java.lang.AssertionError: 
Expected: is <400>
     but: was <201>
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
at com.rest.api.PlaceOrderApi.test_04_verify_order_not_placed_with_incorrect_location_of_one_stop(PlaceOrderApi.java:75)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- test_04_verify_order_not_placed_with_incorrect_location_of_one_stop -->
  <testcase name="test_04_verify_order_not_placed_with_incorrect_location_of_one_stop" time="0.816" classname="com.rest.api.PlaceOrderApi">
    <failure type="java.lang.AssertionError" message="
Expected: is &amp;lt;400&amp;gt;
     but: was &amp;lt;201&amp;gt;">
      <![CDATA[java.lang.AssertionError: 
Expected: is <400>
     but: was <201>
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
at com.rest.api.PlaceOrderApi.test_04_verify_order_not_placed_with_incorrect_location_of_one_stop(PlaceOrderApi.java:75)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- test_04_verify_order_not_placed_with_incorrect_location_of_one_stop -->
  <testcase name="test_05_verify_order_not_placed_with_incorrect_locations_of_stops" time="0.775" classname="com.rest.api.PlaceOrderApi">
    <failure type="java.lang.AssertionError" message="
Expected: is &amp;lt;400&amp;gt;
     but: was &amp;lt;201&amp;gt;">
      <![CDATA[java.lang.AssertionError: 
Expected: is <400>
     but: was <201>
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
at com.rest.api.PlaceOrderApi.test_05_verify_order_not_placed_with_incorrect_locations_of_stops(PlaceOrderApi.java:98)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- test_05_verify_order_not_placed_with_incorrect_locations_of_stops -->
  <testcase name="test_05_verify_order_not_placed_with_incorrect_locations_of_stops" time="0.861" classname="com.rest.api.PlaceOrderApi">
    <failure type="java.lang.AssertionError" message="
Expected: is &amp;lt;400&amp;gt;
     but: was &amp;lt;201&amp;gt;">
      <![CDATA[java.lang.AssertionError: 
Expected: is <400>
     but: was <201>
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
at com.rest.api.PlaceOrderApi.test_05_verify_order_not_placed_with_incorrect_locations_of_stops(PlaceOrderApi.java:98)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- test_05_verify_order_not_placed_with_incorrect_locations_of_stops -->
  <testcase name="test_06_verify_order_not_placed_with_incorrect_end_point" time="0.024" classname="com.rest.api.PlaceOrderApi"/>
  <testcase name="test_06_verify_order_not_placed_with_incorrect_end_point" time="0.024" classname="com.rest.api.PlaceOrderApi"/>
  <testcase name="test_06_verify_order_not_placed_with_incorrect_end_point" time="0.025" classname="com.rest.api.PlaceOrderApi"/>
  <testcase name="test_06_verify_order_not_placed_with_incorrect_end_point" time="0.042" classname="com.rest.api.PlaceOrderApi"/>
  <testcase name="test_06_verify_order_not_placed_with_incorrect_end_point" time="0.02" classname="com.rest.api.PlaceOrderApi"/>
  <testcase name="test_06_verify_order_not_placed_with_incorrect_end_point" time="0.025" classname="com.rest.api.PlaceOrderApi"/>
  <testcase name="test_06_verify_order_not_placed_with_incorrect_end_point" time="0.021" classname="com.rest.api.PlaceOrderApi"/>
  <testcase name="test_07_verify_order_not_placed_in_past_time" time="0.041" classname="com.rest.api.PlaceOrderApi"/>
  <testcase name="test_08_verify_order_not_placed_with_identical_two_stops" time="1.355" classname="com.rest.api.PlaceOrderApi">
    <failure type="java.lang.AssertionError" message="
Expected: is &amp;lt;400&amp;gt;
     but: was &amp;lt;201&amp;gt;">
      <![CDATA[java.lang.AssertionError: 
Expected: is <400>
     but: was <201>
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
at com.rest.api.PlaceOrderApi.test_08_verify_order_not_placed_with_identical_two_stops(PlaceOrderApi.java:154)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- test_08_verify_order_not_placed_with_identical_two_stops -->
  <testcase name="test_01_verify_retrieve_valid_order_with_id" time="0.0" classname="com.rest.api.FetchOrderApi">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 0, Size: 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at common.utils.JsonUtil.placeOrderJson(JsonUtil.java:19)
at com.rest.api.FetchOrderApi.test_01_verify_retrieve_valid_order_with_id(FetchOrderApi.java:27)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- test_01_verify_retrieve_valid_order_with_id -->
  <testcase name="test_02_verify_order_not_retrieved_with_invalid_order_id" time="0.043" classname="com.rest.api.FetchOrderApi"/>
  <testcase name="test_02_verify_order_not_retrieved_with_invalid_order_id" time="0.019" classname="com.rest.api.FetchOrderApi"/>
  <testcase name="test_02_verify_order_not_retrieved_with_invalid_order_id" time="0.02" classname="com.rest.api.FetchOrderApi"/>
  <testcase name="test_02_verify_order_not_retrieved_with_invalid_order_id" time="0.02" classname="com.rest.api.FetchOrderApi"/>
  <testcase name="test_02_verify_order_not_retrieved_with_invalid_order_id" time="0.021" classname="com.rest.api.FetchOrderApi"/>
  <testcase name="test_02_verify_order_not_retrieved_with_invalid_order_id" time="0.025" classname="com.rest.api.FetchOrderApi"/>
  <testcase name="test_03_verify_order_not_retrieved_with_invalid_end_point" time="0.024" classname="com.rest.api.FetchOrderApi"/>
  <testcase name="test_03_verify_order_not_retrieved_with_invalid_end_point" time="0.021" classname="com.rest.api.FetchOrderApi"/>
  <testcase name="test_03_verify_order_not_retrieved_with_invalid_end_point" time="0.019" classname="com.rest.api.FetchOrderApi"/>
  <testcase name="test_03_verify_order_not_retrieved_with_invalid_end_point" time="0.023" classname="com.rest.api.FetchOrderApi"/>
  <testcase name="test_03_verify_order_not_retrieved_with_invalid_end_point" time="0.021" classname="com.rest.api.FetchOrderApi"/>
  <testcase name="test_03_verify_order_not_retrieved_with_invalid_end_point" time="0.023" classname="com.rest.api.FetchOrderApi"/>
  <testcase name="test_03_verify_order_not_retrieved_with_invalid_end_point" time="0.022" classname="com.rest.api.FetchOrderApi"/>
  <testcase name="test_01_verify_cancel_an_assigned_order_with_specific_order_id" time="0.001" classname="com.rest.api.CancelOrderPutApi">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 0, Size: 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at common.utils.JsonUtil.placeOrderJson(JsonUtil.java:19)
at com.rest.api.CancelOrderPutApi.test_01_verify_cancel_an_assigned_order_with_specific_order_id(CancelOrderPutApi.java:26)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- test_01_verify_cancel_an_assigned_order_with_specific_order_id -->
  <testcase name="test_02_verify_cancel_an_ongoing_order_with_specific_order_id" time="0.0" classname="com.rest.api.CancelOrderPutApi">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 0, Size: 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at common.utils.JsonUtil.placeOrderJson(JsonUtil.java:19)
at com.rest.api.CancelOrderPutApi.test_02_verify_cancel_an_ongoing_order_with_specific_order_id(CancelOrderPutApi.java:61)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- test_02_verify_cancel_an_ongoing_order_with_specific_order_id -->
  <testcase name="test_03_verify_order_not_cancelled_for_an_already_completed_order_with_specific_order_id" time="0.001" classname="com.rest.api.CancelOrderPutApi">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 0, Size: 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at common.utils.JsonUtil.placeOrderJson(JsonUtil.java:19)
at com.rest.api.CancelOrderPutApi.test_03_verify_order_not_cancelled_for_an_already_completed_order_with_specific_order_id(CancelOrderPutApi.java:103)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- test_03_verify_order_not_cancelled_for_an_already_completed_order_with_specific_order_id -->
  <testcase name="test_04_verify_order_not_cancelled_an_already_cancelled_order_with_specific_order_id" time="0.001" classname="com.rest.api.CancelOrderPutApi">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 0, Size: 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at common.utils.JsonUtil.placeOrderJson(JsonUtil.java:19)
at com.rest.api.CancelOrderPutApi.test_04_verify_order_not_cancelled_an_already_cancelled_order_with_specific_order_id(CancelOrderPutApi.java:146)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- test_04_verify_order_not_cancelled_an_already_cancelled_order_with_specific_order_id -->
  <testcase name="test_05_verify_order_not_cancelled_with_invalid_order_id" time="0.035" classname="com.rest.api.CancelOrderPutApi"/>
  <testcase name="test_05_verify_order_not_cancelled_with_invalid_order_id" time="0.022" classname="com.rest.api.CancelOrderPutApi"/>
  <testcase name="test_05_verify_order_not_cancelled_with_invalid_order_id" time="0.02" classname="com.rest.api.CancelOrderPutApi"/>
  <testcase name="test_05_verify_order_not_cancelled_with_invalid_order_id" time="0.02" classname="com.rest.api.CancelOrderPutApi"/>
  <testcase name="test_05_verify_order_not_cancelled_with_invalid_order_id" time="0.031" classname="com.rest.api.CancelOrderPutApi"/>
  <testcase name="test_05_verify_order_not_cancelled_with_invalid_order_id" time="0.017" classname="com.rest.api.CancelOrderPutApi"/>
  <testcase name="test_06_verify_order_not_cancelled_with_invalid_end_point" time="0.018" classname="com.rest.api.CancelOrderPutApi"/>
  <testcase name="test_06_verify_order_not_cancelled_with_invalid_end_point" time="0.015" classname="com.rest.api.CancelOrderPutApi"/>
  <testcase name="test_06_verify_order_not_cancelled_with_invalid_end_point" time="0.02" classname="com.rest.api.CancelOrderPutApi"/>
  <testcase name="test_06_verify_order_not_cancelled_with_invalid_end_point" time="0.035" classname="com.rest.api.CancelOrderPutApi"/>
  <testcase name="test_06_verify_order_not_cancelled_with_invalid_end_point" time="0.021" classname="com.rest.api.CancelOrderPutApi"/>
  <testcase name="test_06_verify_order_not_cancelled_with_invalid_end_point" time="0.02" classname="com.rest.api.CancelOrderPutApi"/>
  <testcase name="test_06_verify_order_not_cancelled_with_invalid_end_point" time="0.018" classname="com.rest.api.CancelOrderPutApi"/>
  <testcase name="test_06_verify_order_not_cancelled_with_invalid_end_point" time="0.034" classname="com.rest.api.CancelOrderPutApi"/>
  <testcase name="test_07_verify_order_not_cancelled_without_placing_it" time="0.015" classname="com.rest.api.CancelOrderPutApi"/>
  <testcase name="test_01_verify_complete_an_ongoing_order_with_specific_order_id" time="0.001" classname="com.rest.api.CompleteOrderPutApi">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 0, Size: 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at common.utils.JsonUtil.placeOrderJson(JsonUtil.java:19)
at com.rest.api.CompleteOrderPutApi.test_01_verify_complete_an_ongoing_order_with_specific_order_id(CompleteOrderPutApi.java:32)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- test_01_verify_complete_an_ongoing_order_with_specific_order_id -->
  <testcase name="test_02_verify_order_not_completed_with_invalid_order_id" time="0.0" classname="com.rest.api.CompleteOrderPutApi">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 0, Size: 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at common.utils.JsonUtil.placeOrderJson(JsonUtil.java:19)
at com.rest.api.CompleteOrderPutApi.test_02_verify_order_not_completed_with_invalid_order_id(CompleteOrderPutApi.java:68)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- test_02_verify_order_not_completed_with_invalid_order_id -->
  <testcase name="test_02_verify_order_not_completed_with_invalid_order_id" time="0.001" classname="com.rest.api.CompleteOrderPutApi">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 0, Size: 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at common.utils.JsonUtil.placeOrderJson(JsonUtil.java:19)
at com.rest.api.CompleteOrderPutApi.test_02_verify_order_not_completed_with_invalid_order_id(CompleteOrderPutApi.java:68)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- test_02_verify_order_not_completed_with_invalid_order_id -->
  <testcase name="test_02_verify_order_not_completed_with_invalid_order_id" time="0.0" classname="com.rest.api.CompleteOrderPutApi">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 0, Size: 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at common.utils.JsonUtil.placeOrderJson(JsonUtil.java:19)
at com.rest.api.CompleteOrderPutApi.test_02_verify_order_not_completed_with_invalid_order_id(CompleteOrderPutApi.java:68)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- test_02_verify_order_not_completed_with_invalid_order_id -->
  <testcase name="test_02_verify_order_not_completed_with_invalid_order_id" time="0.001" classname="com.rest.api.CompleteOrderPutApi">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 0, Size: 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at common.utils.JsonUtil.placeOrderJson(JsonUtil.java:19)
at com.rest.api.CompleteOrderPutApi.test_02_verify_order_not_completed_with_invalid_order_id(CompleteOrderPutApi.java:68)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- test_02_verify_order_not_completed_with_invalid_order_id -->
  <testcase name="test_02_verify_order_not_completed_with_invalid_order_id" time="0.0" classname="com.rest.api.CompleteOrderPutApi">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 0, Size: 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at common.utils.JsonUtil.placeOrderJson(JsonUtil.java:19)
at com.rest.api.CompleteOrderPutApi.test_02_verify_order_not_completed_with_invalid_order_id(CompleteOrderPutApi.java:68)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- test_02_verify_order_not_completed_with_invalid_order_id -->
  <testcase name="test_02_verify_order_not_completed_with_invalid_order_id" time="0.001" classname="com.rest.api.CompleteOrderPutApi">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 0, Size: 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at common.utils.JsonUtil.placeOrderJson(JsonUtil.java:19)
at com.rest.api.CompleteOrderPutApi.test_02_verify_order_not_completed_with_invalid_order_id(CompleteOrderPutApi.java:68)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- test_02_verify_order_not_completed_with_invalid_order_id -->
  <testcase name="test_03_verify_order_not_completed_with_invalid_end_point" time="0.0" classname="com.rest.api.CompleteOrderPutApi">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 0, Size: 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at common.utils.JsonUtil.placeOrderJson(JsonUtil.java:19)
at com.rest.api.CompleteOrderPutApi.test_03_verify_order_not_completed_with_invalid_end_point(CompleteOrderPutApi.java:94)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- test_03_verify_order_not_completed_with_invalid_end_point -->
  <testcase name="test_03_verify_order_not_completed_with_invalid_end_point" time="0.007" classname="com.rest.api.CompleteOrderPutApi">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 0, Size: 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at common.utils.JsonUtil.placeOrderJson(JsonUtil.java:19)
at com.rest.api.CompleteOrderPutApi.test_03_verify_order_not_completed_with_invalid_end_point(CompleteOrderPutApi.java:94)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- test_03_verify_order_not_completed_with_invalid_end_point -->
  <testcase name="test_03_verify_order_not_completed_with_invalid_end_point" time="0.001" classname="com.rest.api.CompleteOrderPutApi">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 0, Size: 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at common.utils.JsonUtil.placeOrderJson(JsonUtil.java:19)
at com.rest.api.CompleteOrderPutApi.test_03_verify_order_not_completed_with_invalid_end_point(CompleteOrderPutApi.java:94)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- test_03_verify_order_not_completed_with_invalid_end_point -->
  <testcase name="test_03_verify_order_not_completed_with_invalid_end_point" time="0.001" classname="com.rest.api.CompleteOrderPutApi">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 0, Size: 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at common.utils.JsonUtil.placeOrderJson(JsonUtil.java:19)
at com.rest.api.CompleteOrderPutApi.test_03_verify_order_not_completed_with_invalid_end_point(CompleteOrderPutApi.java:94)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- test_03_verify_order_not_completed_with_invalid_end_point -->
  <testcase name="test_03_verify_order_not_completed_with_invalid_end_point" time="0.001" classname="com.rest.api.CompleteOrderPutApi">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 0, Size: 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at common.utils.JsonUtil.placeOrderJson(JsonUtil.java:19)
at com.rest.api.CompleteOrderPutApi.test_03_verify_order_not_completed_with_invalid_end_point(CompleteOrderPutApi.java:94)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- test_03_verify_order_not_completed_with_invalid_end_point -->
  <testcase name="test_03_verify_order_not_completed_with_invalid_end_point" time="0.001" classname="com.rest.api.CompleteOrderPutApi">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 0, Size: 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at common.utils.JsonUtil.placeOrderJson(JsonUtil.java:19)
at com.rest.api.CompleteOrderPutApi.test_03_verify_order_not_completed_with_invalid_end_point(CompleteOrderPutApi.java:94)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- test_03_verify_order_not_completed_with_invalid_end_point -->
  <testcase name="test_03_verify_order_not_completed_with_invalid_end_point" time="0.001" classname="com.rest.api.CompleteOrderPutApi">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 0, Size: 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at common.utils.JsonUtil.placeOrderJson(JsonUtil.java:19)
at com.rest.api.CompleteOrderPutApi.test_03_verify_order_not_completed_with_invalid_end_point(CompleteOrderPutApi.java:94)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- test_03_verify_order_not_completed_with_invalid_end_point -->
  <testcase name="test_03_verify_order_not_completed_with_invalid_end_point" time="0.0" classname="com.rest.api.CompleteOrderPutApi">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 0, Size: 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at common.utils.JsonUtil.placeOrderJson(JsonUtil.java:19)
at com.rest.api.CompleteOrderPutApi.test_03_verify_order_not_completed_with_invalid_end_point(CompleteOrderPutApi.java:94)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- test_03_verify_order_not_completed_with_invalid_end_point -->
  <testcase name="test_04_verify_order_not_completed_without_placing_it" time="0.019" classname="com.rest.api.CompleteOrderPutApi"/>
  <testcase name="test_05_verify_order_not_completed_for_an_already_completed_order_with_specific_order_id" time="0.0" classname="com.rest.api.CompleteOrderPutApi">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 0, Size: 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at common.utils.JsonUtil.placeOrderJson(JsonUtil.java:19)
at com.rest.api.CompleteOrderPutApi.test_05_verify_order_not_completed_for_an_already_completed_order_with_specific_order_id(CompleteOrderPutApi.java:135)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- test_05_verify_order_not_completed_for_an_already_completed_order_with_specific_order_id -->
  <testcase name="test_01_verify_take_order_with_specific_order_id" time="0.001" classname="com.rest.api.TakeOrderPutApi">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 0, Size: 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at common.utils.JsonUtil.placeOrderJson(JsonUtil.java:19)
at com.rest.api.TakeOrderPutApi.test_01_verify_take_order_with_specific_order_id(TakeOrderPutApi.java:33)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- test_01_verify_take_order_with_specific_order_id -->
  <testcase name="test_02_verify_order_not_taken_with_invalid_order_id" time="0.037" classname="com.rest.api.TakeOrderPutApi"/>
  <testcase name="test_02_verify_order_not_taken_with_invalid_order_id" time="0.018" classname="com.rest.api.TakeOrderPutApi"/>
  <testcase name="test_02_verify_order_not_taken_with_invalid_order_id" time="0.018" classname="com.rest.api.TakeOrderPutApi"/>
  <testcase name="test_02_verify_order_not_taken_with_invalid_order_id" time="0.018" classname="com.rest.api.TakeOrderPutApi"/>
  <testcase name="test_02_verify_order_not_taken_with_invalid_order_id" time="0.03" classname="com.rest.api.TakeOrderPutApi"/>
  <testcase name="test_02_verify_order_not_taken_with_invalid_order_id" time="0.02" classname="com.rest.api.TakeOrderPutApi"/>
  <testcase name="test_03_verify_order_not_taken_with_invalid_end_point" time="0.019" classname="com.rest.api.TakeOrderPutApi"/>
  <testcase name="test_03_verify_order_not_taken_with_invalid_end_point" time="0.018" classname="com.rest.api.TakeOrderPutApi"/>
  <testcase name="test_03_verify_order_not_taken_with_invalid_end_point" time="0.018" classname="com.rest.api.TakeOrderPutApi"/>
  <testcase name="test_03_verify_order_not_taken_with_invalid_end_point" time="0.035" classname="com.rest.api.TakeOrderPutApi"/>
  <testcase name="test_03_verify_order_not_taken_with_invalid_end_point" time="0.017" classname="com.rest.api.TakeOrderPutApi"/>
  <testcase name="test_03_verify_order_not_taken_with_invalid_end_point" time="0.022" classname="com.rest.api.TakeOrderPutApi"/>
  <testcase name="test_03_verify_order_not_taken_with_invalid_end_point" time="0.023" classname="com.rest.api.TakeOrderPutApi"/>
  <testcase name="test_03_verify_order_not_taken_with_invalid_end_point" time="0.036" classname="com.rest.api.TakeOrderPutApi"/>
  <testcase name="test_04_verify_order_not_taken_without_placing_it" time="0.022" classname="com.rest.api.TakeOrderPutApi"/>
  <testcase name="@BeforeSuite initialize" time="0.0" classname="com.rest.api.BaseClass">
    <ignored/>
  </testcase> <!-- @BeforeSuite initialize -->
  <testcase name="@BeforeSuite initialize" time="0.0" classname="com.rest.api.BaseClass">
    <ignored/>
  </testcase> <!-- @BeforeSuite initialize -->
  <testcase name="@BeforeSuite initialize" time="0.0" classname="com.rest.api.BaseClass">
    <ignored/>
  </testcase> <!-- @BeforeSuite initialize -->
  <testcase name="@BeforeSuite initialize" time="0.0" classname="com.rest.api.BaseClass">
    <ignored/>
  </testcase> <!-- @BeforeSuite initialize -->
</testsuite> <!-- Regression-Suite -->
