<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="sandeep406701" name="com.rest.api.putApiCancelOrder" tests="19" failures="1" timestamp="08 Jan 2019 07:30:24 GMT" time="16.090" errors="0">
  <testcase name="test_06_verify_order_not_cancelled_with_invalid_end_point" time="3.579" classname="com.rest.api.putApiCancelOrder"/>
  <testcase name="test_07_verify_order_not_cancelled_without_placing_it" time="0.022" classname="com.rest.api.putApiCancelOrder"/>
  <testcase name="test_04_verify_order_not_cancelled_an_already_cancelled_order_with_specific_order_id" time="1.261" classname="com.rest.api.putApiCancelOrder">
    <failure type="java.lang.AssertionError" message="
Expected: is &lt;400&gt;
     but: was &lt;200&gt;">
      <![CDATA[java.lang.AssertionError: 
Expected: is <400>
     but: was <200>
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
at com.rest.api.putApiCancelOrder.test_04_verify_order_not_cancelled_an_already_cancelled_order_with_specific_order_id(putApiCancelOrder.java:268)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test_04_verify_order_not_cancelled_an_already_cancelled_order_with_specific_order_id -->
  <testcase name="test_02_verify_cancel_an_ongoing_order_with_specific_order_id" time="0.759" classname="com.rest.api.putApiCancelOrder"/>
  <testcase name="test_06_verify_order_not_cancelled_with_invalid_end_point" time="0.579" classname="com.rest.api.putApiCancelOrder"/>
  <testcase name="test_05_verify_order_not_cancelled_with_invalid_order_id" time="0.948" classname="com.rest.api.putApiCancelOrder"/>
  <testcase name="test_05_verify_order_not_cancelled_with_invalid_order_id" time="0.671" classname="com.rest.api.putApiCancelOrder"/>
  <testcase name="test_05_verify_order_not_cancelled_with_invalid_order_id" time="0.629" classname="com.rest.api.putApiCancelOrder"/>
  <testcase name="test_06_verify_order_not_cancelled_with_invalid_end_point" time="0.666" classname="com.rest.api.putApiCancelOrder"/>
  <testcase name="test_05_verify_order_not_cancelled_with_invalid_order_id" time="0.640" classname="com.rest.api.putApiCancelOrder"/>
  <testcase name="test_06_verify_order_not_cancelled_with_invalid_end_point" time="0.898" classname="com.rest.api.putApiCancelOrder"/>
  <testcase name="test_06_verify_order_not_cancelled_with_invalid_end_point" time="0.694" classname="com.rest.api.putApiCancelOrder"/>
  <testcase name="test_06_verify_order_not_cancelled_with_invalid_end_point" time="0.608" classname="com.rest.api.putApiCancelOrder"/>
  <testcase name="test_03_verify_order_not_cancelled_for_an_already_completed_order_with_specific_order_id" time="0.692" classname="com.rest.api.putApiCancelOrder"/>
  <testcase name="test_05_verify_order_not_cancelled_with_invalid_order_id" time="0.728" classname="com.rest.api.putApiCancelOrder"/>
  <testcase name="test_05_verify_order_not_cancelled_with_invalid_order_id" time="0.695" classname="com.rest.api.putApiCancelOrder"/>
  <testcase name="test_06_verify_order_not_cancelled_with_invalid_end_point" time="0.684" classname="com.rest.api.putApiCancelOrder"/>
  <testcase name="test_01_verify_cancel_an_assigned_order_with_specific_order_id" time="0.723" classname="com.rest.api.putApiCancelOrder"/>
  <testcase name="test_06_verify_order_not_cancelled_with_invalid_end_point" time="0.614" classname="com.rest.api.putApiCancelOrder"/>
</testsuite> <!-- com.rest.api.putApiCancelOrder -->
