<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="sandeep406701" name="com.rest.api.CancelOrderPutApi" tests="19" failures="1" timestamp="09 Jan 2019 10:27:42 GMT" time="4.902" errors="0">
  <testcase name="test_06_verify_order_not_cancelled_with_invalid_end_point" time="0.022" classname="com.rest.api.CancelOrderPutApi"/>
  <testcase name="test_06_verify_order_not_cancelled_with_invalid_end_point" time="0.023" classname="com.rest.api.CancelOrderPutApi"/>
  <testcase name="test_05_verify_order_not_cancelled_with_invalid_order_id" time="0.022" classname="com.rest.api.CancelOrderPutApi"/>
  <testcase name="test_06_verify_order_not_cancelled_with_invalid_end_point" time="0.017" classname="com.rest.api.CancelOrderPutApi"/>
  <testcase name="test_06_verify_order_not_cancelled_with_invalid_end_point" time="0.019" classname="com.rest.api.CancelOrderPutApi"/>
  <testcase name="test_04_verify_order_not_cancelled_an_already_cancelled_order_with_specific_order_id" time="0.385" classname="com.rest.api.CancelOrderPutApi">
    <failure type="java.lang.AssertionError" message="
Expected: is &lt;422&gt;
     but: was &lt;200&gt;">
      <![CDATA[java.lang.AssertionError: 
Expected: is <422>
     but: was <200>
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
at com.rest.api.CancelOrderPutApi.test_04_verify_order_not_cancelled_an_already_cancelled_order_with_specific_order_id(CancelOrderPutApi.java:178)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test_04_verify_order_not_cancelled_an_already_cancelled_order_with_specific_order_id -->
  <testcase name="test_01_verify_cancel_an_assigned_order_with_specific_order_id" time="3.147" classname="com.rest.api.CancelOrderPutApi"/>
  <testcase name="test_06_verify_order_not_cancelled_with_invalid_end_point" time="0.024" classname="com.rest.api.CancelOrderPutApi"/>
  <testcase name="test_06_verify_order_not_cancelled_with_invalid_end_point" time="0.020" classname="com.rest.api.CancelOrderPutApi"/>
  <testcase name="test_05_verify_order_not_cancelled_with_invalid_order_id" time="0.031" classname="com.rest.api.CancelOrderPutApi"/>
  <testcase name="test_02_verify_cancel_an_ongoing_order_with_specific_order_id" time="0.610" classname="com.rest.api.CancelOrderPutApi"/>
  <testcase name="test_05_verify_order_not_cancelled_with_invalid_order_id" time="0.021" classname="com.rest.api.CancelOrderPutApi"/>
  <testcase name="test_05_verify_order_not_cancelled_with_invalid_order_id" time="0.025" classname="com.rest.api.CancelOrderPutApi"/>
  <testcase name="test_03_verify_order_not_cancelled_for_an_already_completed_order_with_specific_order_id" time="0.422" classname="com.rest.api.CancelOrderPutApi"/>
  <testcase name="test_06_verify_order_not_cancelled_with_invalid_end_point" time="0.027" classname="com.rest.api.CancelOrderPutApi"/>
  <testcase name="test_06_verify_order_not_cancelled_with_invalid_end_point" time="0.018" classname="com.rest.api.CancelOrderPutApi"/>
  <testcase name="test_05_verify_order_not_cancelled_with_invalid_order_id" time="0.020" classname="com.rest.api.CancelOrderPutApi"/>
  <testcase name="test_07_verify_order_not_cancelled_without_placing_it" time="0.026" classname="com.rest.api.CancelOrderPutApi"/>
  <testcase name="test_05_verify_order_not_cancelled_with_invalid_order_id" time="0.023" classname="com.rest.api.CancelOrderPutApi"/>
</testsuite> <!-- com.rest.api.CancelOrderPutApi -->
